### ISSUE TITLE
2.2.8 checklist

### ISSUE THREAD

**Issue by halamix2** [PHP-Outburst/myUPB#48]
We need to do some things before release in the distant future:  
### To Do
- [ ] fix all known bugs is our primary target (I think)

### Cleanup
- [ ] unify all boilerplate comments (authors, version etc.)
- [ ] unify tabs/spaces (open question)

### Closing
- [ ] Set version to 2.2.8 in all files
    - [ ] boilerplate comments
    - [ ] installer
    - [ ] updater
    - [ ] ~documentation (if we have any)~
- [ ] update changelog
- [ ] remove debug code from index.php (E_ALL)
