### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by halamix2** [PHP-Outburst/myUPB#61]
Currently we have two readme files which may be disorienting

### To-do
- [ ] merge readme.md and readme.txt
- [ ] add INSTALL.md file (extract from readme.txt)
- [ ] move history.txt to wiki
- [ ] add information about project to composer.json file
- [ ] comment all classes (using PHPDocumentor syntax) (this one will take time)

**Comment by sarnobat** [comment]
This would be good. Particularly merging the readme's. The .md one doesn't show all the installation steps but that's the one everyone sees when they navigate to the github web view.

**Comment by sarnobat** [comment]
Even though wiki documentation is welcome, I doubt that is source controlled so migrating to another repo in the future would be more work.
